---
name: Gleam lsp
description: |
  A friendly language for building type-safe, scalable systems!
homepage: https://gleam.run/
licenses:
  - Apache-2.0
languages:
  - Gleam
categories:
  - LSP

source:
  id: pkg:github.com/gleam-lang/gleam@v0.28.0
  asset:
    - target: linux_x64_gnu
      file: gleam-v0.28.0-x86_64-unknown-linux-gnu.tar.gz
      bin: gleam
    - target: linux_arm64_musl
      file: gleam-v0.28.0-aarch64-unknown-linux-musl.tar.gz
      bin: gleam
    - target: linux_x64_musl
      file: gleam-v0.28.0-x86_64-unknown-linux-musl.tar.gz
      bin: gleam
    - target: darwin_x64
      file: gleam-v0.28.0-x86_64-apple-darwin.tar.gz
      bin: gleam
    - target: darwin_arm64
      file: gleam-v0.28.0-aarch64-apple-darwin.tar.gz
      bin: gleam
    - target: win_x64
      file: gleam-v0.28.0-x86_64-pc-windows-msvc.zip
      bin: gleam.exe
    - target: win_arm64

bin:
  gleam lsp: "{{source.asset.bin}}"
